### ISSUE TITLE
Code in console possible broken.

### ISSUE THREAD

**Issue by mmeoak240** [learn-co-curriculum/phase-0-pac-2-intro#2]
### Canvas Link

https://learning.flatironschool.com/courses/4976/pages/programming-as-conversation-2-introduction?module_item_id=345693

### Concern

let favoriteNumber = 0;
while (favoriteNumber < 10) {
  favoriteNumber = favoriteNumber + 1
}
favoriteNumber;

Is returning 10 as the value.

**Comment by graciemcguire** [comment]
Hi @mmeoak240 !

10 is the correct return value in this code. 
You are declaring the initial value of favoriteNumber to start at zero. 
Then you loop over it and say "while the value of favoriteNumber is less than 10, I am going to increment it by one.
Then, when you have incremented it be 10, the loop ends and you return favoriteNumber. 
 Try putting some `console.log`'s in to your code to see it increment everytime!

```js
let favoriteNumber = 0;
console.log('favoriteNumber before loop: ', favoriteNumber)

while (favoriteNumber < 10) {
  favoriteNumber = favoriteNumber + 1
  console.log('favoriteNumber being incremented inside of loop: ', favoriteNumber)
}
console.log('favoriteNumber after the loop ends: ', favoriteNumber)
favoriteNumber;
```

Hope this helps!
