### ISSUE TITLE
Typo in Replit Code

### ISSUE THREAD

**Issue by bitz820** [learn-co-curriculum/phase-0-pac-2-intro#5]
### Canvas Link

https://learning.flatironschool.com/courses/5470/pages/programming-as-conversation-2-introduction?module_item_id=363172

### Concern

![Screen Shot 2022-02-19 at 3 35 44 PM](https://user-images.githubusercontent.com/96665047/154818314-41d921b1-31d2-477e-98a8-c9e6be93b83b.png)

Class example lists favoriteNumber as a const but the value is unable to be reassigned within the if statement as a result.

I believe it should be _let_ favoriteNumber =

**Comment by lizbur10** [comment]
Thanks for catching this @bitz820! It has now been fixed 💙
